##
## Name: laravel-test-pokeapi
## Dockerfile to build a LEMP stack image for querying purposes to PockeAPI.
## Author: https://about.me/henrycv
##
## Description: this image contains the version 7.3 of PHP-FPM.
##

version: '3'
services:

  # #PHP Service
  docker-php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: docker-php
    container_name: ${PREFIX_PROJECT}docker-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /usr/share/nginx/html
    links:
      - docker-mysql
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - lemp-network

  #Nginx Service
  docker-nginx:
    image: nginx:1.17.5
    container_name: ${PREFIX_PROJECT}docker-nginx
    links:
      - docker-php
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - lemp-network

  #MySQL Service
  docker-mysql:
    image: mysql:8.0.18
    container_name: ${PREFIX_PROJECT}docker-mysql
    tty: true
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lemp-network

#Docker Networks
networks:
  lemp-network:
    driver: bridge